# Generated by Django 2.2.3 on 2019-07-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190710_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='owner',
        ),
    ]
