# Generated by Django 2.2.3 on 2019-07-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190711_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='owner',
            new_name='user',
        ),
    ]
