# Generated by Django 2.2.3 on 2019-07-13 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190712_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_photo', to='app.Photo'),
        ),
        migrations.AlterField(
            model_name='good',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
